# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10 
    commands:
      - echo Installing Mocha...
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - echo Build started on `date` 
      - docker build -t sin/sin-app:1.0 .
      - docker tag sin/sin-app:1.0 638274162892.dkr.ecr.us-east-1.amazonaws.com/sin-app:1.0
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push 638274162892.dkr.ecr.us-east-1.amazonaws.com/sin-app:1.0
artifacts:
  files:
    - app.js
    - index.html
    - package.json
    - node_modules/async/*
    - node_modules/lodash/*