version: 0.2
env:
  variables:
    image_tag: '2.4'
phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo Build app
  pre_build:
    commands:
      - echo Fazendo login no ECR...
      - rpm -ivh https://github.com/aquasecurity/trivy/releases/download/v0.18.3/trivy_0.18.3_Linux-64bit.rpm
      - $(aws ecr get-login --no-include-email --region us-east-1) 
  build:
    commands:
      - echo Build started on `date` 
      - echo Fazendo o build da imagem do Docker
      - docker build -t sin/sin-app:$image_tag .
      - echo Criando a tag
      - docker tag sin/sin-app:$image_tag 638274162892.dkr.ecr.us-east-1.amazonaws.com/sin-app:$image_tag
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Fazendo o scan da image com o Trivy para identificar vulnerabilidade
      - trivy image sin/sin-app:$image_tag
      - echo Fazendo upload da imagem para o ECR
      - docker push 638274162892.dkr.ecr.us-east-1.amazonaws.com/sin-app:$image_tag
# artifacts:
#   files:
#     - app.js
#     - index.html
#     - package.json
#     - node_modules/async/*
#     - node_modules/lodash/*